Select suggested route
HackYourFuture-CPH/ov-class09-fp pull request #108
Opened 2019-10-10 11:21 UTC by ismailirahim

**Select a suggested route:**
`/api/vessel-reports/:vessel_report_id/select-route/` :POST

Body example:

```
{
  "suggested_route_id": 3
}
```

**Get the selected suggested_rooute:**
`/api/vessel-report/:vessel_report_id/selected-route/ :GET`

2019-10-11 13:26 UTC, zkwsk requested changes
Sorry I forgot to add this to the task on Trello, but could you add the following functionality under when selecting a suggested route?

Please perform a query to get the `vessel_report` associated with the current `suggested_route`. Now write the `eta` from `sugested_routes.eta` to `vessel_reports.eta`.

The purpose of doing this is that we improve the performance by "caching" the last known eta value on the `vessel_report` where it is a little faster to fetch than on `suggested_route`.

2019-10-13 13:38 UTC, zkwsk requested changes
Please add Swagger docs for `/api/vessel-reports/:vessel_report_id/select-route/ :POST` under suggested routes

2019-10-13 14:48 UTC, zkwsk submitted a review, later dismissed
⛱

2019-10-13 14:48 UTC, zkwsk commented on src/server/api/controllers/vessel-reports.controller.js
> +    const getSelectedRouteId = await knex("vessel_reports")
Rename
```suggestion
    const vesselReports = await knex("vessel_reports")
```

2019-10-13 14:48 UTC, zkwsk commented on src/server/api/controllers/vessel-reports.controller.js
> +      getSelectedRouteId[0].selected_route_id !== null
```suggestion
      vesselReports !== 0 &&
      vesselReports[0].selected_route_id !== null
```

2019-10-15 05:14 UTC, Swapna-Sahu submitted a review, later dismissed
Looks good to me

2019-10-15 13:53 UTC, zkwsk approved these changes

2019-10-15 13:54 UTC, zkwsk approved these changes

2019-10-15 13:54 UTC, merged