Add navigation bar
HackYourFuture-CPH/ov-class09-fp pull request #133
Opened 2019-10-16 23:44 UTC by lil2400

https://trello.com/c/Hz9JCVTx/51-primary-navigation-and-header

2019-10-18 15:56 UTC, zkwsk requested changes

2019-10-18 15:56 UTC, zkwsk commented on src/client/components/NavBar.js
> +    backgroundColor: "#FFFFFF"
Can you make it `#0b3c61`

2019-10-18 15:56 UTC, zkwsk commented on src/client/components/NavBar.js
> +          </div>
Let's remove the logo. I know it was in the wireframe, but the logo we have is not suited for that type of use.

2019-10-19 09:06 UTC, Swapna-Sahu submitted a review, later dismissed
looks good to me

2019-10-19 22:50 UTC, zkwsk requested changes
- [x] Please make the links active

- [x] Please add the component to the top of the App.js component

2019-10-19 22:50 UTC, zkwsk commented on src/client/components/NavBar.js
> +          <MenuItem className={classes.MenuItemColor}>ALL VOYAGES</MenuItem>
Please make these links active:

```
<MenuItem className={classes.MenuItemColor}><Link to="/voyages">MAP</Link></MenuItem>
<MenuItem className={classes.MenuItemColor}><Link to="/voyages-summary">START VOYAGE</Link></MenuItem>
<MenuItem className={classes.MenuItemColor}><Link to="/voyages-summary">ALL VOYAGES</Link></MenuItem>
```

2019-10-20 12:28 UTC, zkwsk approved these changes

2019-10-20 12:28 UTC, merged