Organization API
HackYourFuture-CPH/ov-class09-fp pull request #23
Opened 2019-09-11 20:59 UTC by lil2400

Created new endpoint for organization table

2019-09-11 21:25 UTC, zkwsk requested changes

2019-09-12 12:23 UTC, zkwsk requested changes
Found some things I would like changed.

Furthermore, I cannot seem to get `/api/organizations/ :POST` to work. It gives me a 404. I've sent you my request in Postman on Slack. Maybe there is something I'm missing?

2019-09-13 11:17 UTC, bytewiz approved these changes
Looks good to me, could find somethings to improve but let's save that for later :v:

2019-09-13 12:35 UTC, zkwsk approved these changes
Looks very good. Great work 💪

2019-09-13 12:35 UTC, zkwsk commented on src/server/api/controllers/organization.controller.js
> +    logo: logo
Just a heads up. You have a few places where you are doing assignments like this. Could be optimized with destructuring like this:
```
{ name, logo }
```
But it's a really minor improvement.

2019-09-13 12:35 UTC, merged